Main page
SergikEnergy/react-project-39group pull request #10
Opened 2024-05-21 22:14 UTC by IONIN66

2024-05-22 08:32 UTC, SergikEnergy requested changes

2024-05-22 08:32 UTC, SergikEnergy commented on src/components/InputField/InputField.jsx
> +                  <ThumbUpIcon />
вот эту вот всю логику в отдельный компонент - CardList - а внутри него мапить кастомную карточку - тоже отдельный компонент Card

2024-05-22 08:32 UTC, SergikEnergy commented on src/components/InputField/InputField.jsx
> +};
тоже отдельный компонент - все что можно переиспользовать - в отдельные компоненты - старайся никогда не делать компоненты больше 150 строк - это со всей лгикой и т.д. - это условно - если не вкладываешься - значит нужен или кастомный хук - или сделать более мелкте компоненты - это так на будущее

2024-05-22 21:44 UTC, IONIN66 commented on src/components/InputField/InputField.jsx
> +                  <ThumbUpIcon />
Исправлено

2024-05-22 21:44 UTC, IONIN66 commented on src/components/InputField/InputField.jsx
> +};
Исправлено

2024-05-23 06:52 UTC, SergikEnergy approved these changes

2024-05-23 06:52 UTC, SergikEnergy commented on src/components/InputField/NoFound.jsx
> +        </Button>
чуть смущает эта кнопка - ее назначение - ты просто стейт обнуляешь по ней в инпуте?
Как по мне - она не нужна, т.к. ты рисуешь эту карточку - просто когда у тебя не находит продукты - т.е. если products=useProductsSelector(); - по условию products.products.length===0 && !products.error && !loading - а когда у тебя идет успешный поиск - то лоадер - а если есть карточки

2024-05-23 06:52 UTC, SergikEnergy commented on src/firebase/index.js
> +  storageBucket: "YOUR_STORAGE_BUCKET",
ключи верни на место, чтобы сразу логин работал
у тебя д.б. напомню файлик .env - в корне проекта

2024-05-23 21:10 UTC, IONIN66 commented on src/firebase/index.js
> +  storageBucket: "YOUR_STORAGE_BUCKET",
Исправил

2024-05-24 08:31 UTC, SergikEnergy requested changes

2024-05-24 08:31 UTC, SergikEnergy commented on src/components/InputField/SuggestionList.jsx
> +            debouncedSuggestions.map((suggestion, index) => (
убираем все что не надо - SuggestionList теперь не нужен вообще.

2024-05-24 08:31 UTC, SergikEnergy commented on src/hooks/useDebounce.js
export потерял - export const

2024-05-24 08:31 UTC, SergikEnergy commented on src/pages/MainPage/MainPage.jsx
> -
console.logs и комменты убираем по коду - не забыть перед сдачей проверить!!!!

2024-05-24 08:31 UTC, SergikEnergy commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +          alt="Not Found"
добавить кнопку "на Главную" - чтобы нас редиректило на main page

2024-05-24 19:34 UTC, IONIN66 commented on src/hooks/useDebounce.js
Исправил

2024-05-24 21:04 UTC, IONIN66 commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +          alt="Not Found"
сделал

2024-05-24 21:05 UTC, IONIN66 commented on src/components/InputField/SuggestionList.jsx
> +            debouncedSuggestions.map((suggestion, index) => (
сделал

2024-05-24 21:06 UTC, merged